// src/components/vue/CapivvPaywall.vue
<template>
  <ion-content :class="['capivv-paywall', { dark: darkMode }]">
    <div class="paywall-container">
      <!-- Header -->
      <div class="paywall-header">
        <ion-button v-if="showCloseButton" fill="clear" @click="$emit('dismiss')">
          <ion-icon :icon="closeOutline"></ion-icon>
        </ion-button>
        <h1 class="paywall-title">{{ title }}</h1>
        <p v-if="subtitle" class="paywall-subtitle">{{ subtitle }}</p>
      </div>

      <!-- Loading State -->
      <div v-if="loading" class="paywall-loading">
        <ion-spinner></ion-spinner>
        <p>Loading products...</p>
      </div>

      <!-- Error State -->
      <div v-if="error" class="paywall-error">
        <ion-icon :icon="alertCircleOutline" color="danger"></ion-icon>
        <p>{{ error }}</p>
        <ion-button @click="loadProducts">Retry</ion-button>
      </div>

      <!-- Products -->
      <div v-if="!loading && !error" class="paywall-products">
        <ion-card
          v-for="product in products"
          :key="product.identifier"
          :class="{ selected: selectedProduct?.identifier === product.identifier }"
          button
          @click="selectProduct(product)"
        >
          <ion-card-header>
            <ion-card-title>{{ product.title }}</ion-card-title>
            <ion-card-subtitle v-if="product.subscriptionPeriod">
              {{ product.subscriptionPeriod }}
            </ion-card-subtitle>
          </ion-card-header>
          <ion-card-content>
            <p class="product-description">{{ product.description }}</p>
            <div class="product-price">
              <span class="price">{{ product.priceString }}</span>
              <span v-if="product.trialPeriod" class="trial-badge">
                {{ product.trialPeriod }} free trial
              </span>
            </div>
          </ion-card-content>
          <ion-icon
            v-if="selectedProduct?.identifier === product.identifier"
            :icon="checkmarkCircle"
            color="primary"
            class="selected-icon"
          ></ion-icon>
        </ion-card>
      </div>

      <!-- Features List -->
      <div v-if="features.length > 0" class="paywall-features">
        <h3>What you'll get:</h3>
        <ion-list lines="none">
          <ion-item v-for="(feature, index) in features" :key="index">
            <ion-icon :icon="checkmarkCircle" color="success" slot="start"></ion-icon>
            <ion-label>{{ feature }}</ion-label>
          </ion-item>
        </ion-list>
      </div>

      <!-- Purchase Button -->
      <div class="paywall-actions">
        <ion-button
          expand="block"
          size="large"
          :disabled="!selectedProduct || purchasing"
          @click="purchase"
        >
          <ion-spinner v-if="purchasing"></ion-spinner>
          <span v-else>{{ purchaseButtonText || 'Subscribe Now' }}</span>
        </ion-button>

        <ion-button
          v-if="showRestoreButton"
          expand="block"
          fill="clear"
          :disabled="restoring"
          @click="restore"
        >
          <ion-spinner v-if="restoring" name="dots"></ion-spinner>
          <span v-else>Restore Purchases</span>
        </ion-button>
      </div>

      <!-- Footer -->
      <div class="paywall-footer">
        <p class="terms-text">
          <a v-if="termsUrl" @click="openTerms">Terms of Service</a>
          <span v-if="termsUrl && privacyUrl"> • </span>
          <a v-if="privacyUrl" @click="openPrivacy">Privacy Policy</a>
        </p>
        <p v-if="selectedProduct?.productType === 'SUBSCRIPTION'" class="subscription-terms">
          Subscription automatically renews unless cancelled at least 24 hours before the end of the
          current period.
        </p>
      </div>
    </div>
  </ion-content>
</template>

<script lang="ts">
import { defineComponent, ref, onMounted, onUnmounted, PropType } from 'vue';
import {
  IonContent,
  IonButton,
  IonIcon,
  IonSpinner,
  IonCard,
  IonCardHeader,
  IonCardTitle,
  IonCardSubtitle,
  IonCardContent,
  IonList,
  IonItem,
  IonLabel,
} from '@ionic/vue';
import { closeOutline, checkmarkCircle, alertCircleOutline } from 'ionicons/icons';
import { Capivv, Product, Offering, PurchaseResult, ProductType } from '../../index';
import type { PluginListenerHandle } from '@capacitor/core';

/**
 * Capivv Paywall Component for Ionic Vue
 *
 * A ready-to-use paywall component that displays available products
 * and handles the purchase flow.
 *
 * @example
 * ```vue
 * <CapivvPaywall
 *   offering-id="default"
 *   :show-restore-button="true"
 *   @purchase-complete="onPurchaseComplete"
 *   @dismiss="closePaywall"
 * />
 * ```
 */
export default defineComponent({
  name: 'CapivvPaywall',
  components: {
    IonContent,
    IonButton,
    IonIcon,
    IonSpinner,
    IonCard,
    IonCardHeader,
    IonCardTitle,
    IonCardSubtitle,
    IonCardContent,
    IonList,
    IonItem,
    IonLabel,
  },
  props: {
    /** The offering ID to display products from */
    offeringId: {
      type: String,
      default: 'default',
    },
    /** Title displayed at the top of the paywall */
    title: {
      type: String,
      default: 'Unlock Premium',
    },
    /** Subtitle displayed below the title */
    subtitle: {
      type: String,
      default: '',
    },
    /** Whether to show the close button */
    showCloseButton: {
      type: Boolean,
      default: true,
    },
    /** Whether to show the restore purchases button */
    showRestoreButton: {
      type: Boolean,
      default: true,
    },
    /** List of features to display */
    features: {
      type: Array as PropType<string[]>,
      default: () => [],
    },
    /** Custom text for the purchase button */
    purchaseButtonText: {
      type: String,
      default: 'Subscribe Now',
    },
    /** URL for terms of service */
    termsUrl: {
      type: String,
      default: '',
    },
    /** URL for privacy policy */
    privacyUrl: {
      type: String,
      default: '',
    },
    /** Enable dark mode styling */
    darkMode: {
      type: Boolean,
      default: false,
    },
  },
  emits: ['purchase-complete', 'purchase-failed', 'restore-complete', 'dismiss'],
  setup(props, { emit }) {
    const products = ref<Product[]>([]);
    const selectedProduct = ref<Product | null>(null);
    const loading = ref(true);
    const error = ref<string | null>(null);
    const purchasing = ref(false);
    const restoring = ref(false);
    const listeners = ref<PluginListenerHandle[]>([]);

    const loadProducts = async () => {
      loading.value = true;
      error.value = null;

      try {
        const { offerings } = await Capivv.getOfferings();
        const offering =
          offerings.find((o: Offering) => o.identifier === props.offeringId) || offerings[0];

        if (offering) {
          products.value = offering.products;
          if (offering.products.length > 0) {
            selectedProduct.value = offering.products[0];
          }
        }
      } catch (e) {
        error.value = e instanceof Error ? e.message : 'Failed to load products';
      } finally {
        loading.value = false;
      }
    };

    const setupListeners = async () => {
      const purchaseListener = await Capivv.addListener('purchaseCompleted', (event) => {
        purchasing.value = false;
        emit('purchase-complete', { success: true, transaction: event.transaction });
      });
      listeners.value.push(purchaseListener);

      const failedListener = await Capivv.addListener('purchaseFailed', (event) => {
        purchasing.value = false;
        emit('purchase-failed', { error: event.error });
      });
      listeners.value.push(failedListener);
    };

    const selectProduct = (product: Product) => {
      selectedProduct.value = product;
    };

    const purchase = async () => {
      if (!selectedProduct.value) return;

      purchasing.value = true;

      try {
        const result = await Capivv.purchase({
          productIdentifier: selectedProduct.value.identifier,
          productType: selectedProduct.value.productType as ProductType,
        });

        if (result.success) {
          emit('purchase-complete', result);
        } else {
          emit('purchase-failed', { error: result.error || 'Purchase failed' });
        }
      } catch (e) {
        emit('purchase-failed', { error: e instanceof Error ? e.message : 'Purchase failed' });
      } finally {
        purchasing.value = false;
      }
    };

    const restore = async () => {
      restoring.value = true;

      try {
        await Capivv.restorePurchases();
        emit('restore-complete');
      } catch (e) {
        emit('purchase-failed', { error: e instanceof Error ? e.message : 'Restore failed' });
      } finally {
        restoring.value = false;
      }
    };

    const openTerms = () => {
      if (props.termsUrl) {
        window.open(props.termsUrl, '_blank');
      }
    };

    const openPrivacy = () => {
      if (props.privacyUrl) {
        window.open(props.privacyUrl, '_blank');
      }
    };

    onMounted(async () => {
      await loadProducts();
      await setupListeners();
    });

    onUnmounted(() => {
      listeners.value.forEach((listener) => listener.remove());
    });

    return {
      products,
      selectedProduct,
      loading,
      error,
      purchasing,
      restoring,
      loadProducts,
      selectProduct,
      purchase,
      restore,
      openTerms,
      openPrivacy,
      closeOutline,
      checkmarkCircle,
      alertCircleOutline,
    };
  },
});
</script>

<style scoped>
.capivv-paywall {
  --background: var(--ion-background-color, #ffffff);
}

.capivv-paywall.dark {
  --background: var(--ion-background-color, #1a1a1a);
}

.paywall-container {
  padding: 16px;
  max-width: 500px;
  margin: 0 auto;
}

.paywall-header {
  text-align: center;
  margin-bottom: 24px;
}

.paywall-title {
  font-size: 24px;
  font-weight: 700;
  margin: 16px 0 8px;
}

.paywall-subtitle {
  font-size: 16px;
  color: var(--ion-color-medium);
  margin: 0;
}

.paywall-loading,
.paywall-error {
  text-align: center;
  padding: 48px 16px;
}

.paywall-error ion-icon {
  font-size: 48px;
  margin-bottom: 16px;
}

.paywall-products {
  margin-bottom: 24px;
}

ion-card {
  margin: 12px 0;
  position: relative;
  border: 2px solid transparent;
  transition: border-color 0.2s ease;
}

ion-card.selected {
  border-color: var(--ion-color-primary);
}

.selected-icon {
  position: absolute;
  top: 12px;
  right: 12px;
  font-size: 24px;
}

.product-description {
  color: var(--ion-color-medium);
  margin-bottom: 12px;
}

.product-price {
  display: flex;
  align-items: center;
  gap: 8px;
}

.price {
  font-size: 20px;
  font-weight: 700;
  color: var(--ion-color-primary);
}

.trial-badge {
  background: var(--ion-color-success);
  color: white;
  padding: 4px 8px;
  border-radius: 4px;
  font-size: 12px;
  font-weight: 600;
}

.paywall-features {
  margin-bottom: 24px;
}

.paywall-features h3 {
  margin-bottom: 12px;
  font-weight: 600;
}

.paywall-actions {
  margin-bottom: 24px;
}

.paywall-actions ion-button {
  margin-bottom: 8px;
}

.paywall-footer {
  text-align: center;
}

.terms-text {
  font-size: 14px;
  color: var(--ion-color-medium);
}

.terms-text a {
  color: var(--ion-color-primary);
  cursor: pointer;
}

.subscription-terms {
  font-size: 12px;
  color: var(--ion-color-medium);
  margin-top: 8px;
}
</style>

// src/components/react/CapivvPaywall.tsx
import React, { useState, useEffect, useCallback } from 'react';
import {
  IonContent,
  IonButton,
  IonIcon,
  IonSpinner,
  IonCard,
  IonCardHeader,
  IonCardTitle,
  IonCardSubtitle,
  IonCardContent,
  IonList,
  IonItem,
  IonLabel,
} from '@ionic/react';
import { closeOutline, checkmarkCircle, alertCircleOutline } from 'ionicons/icons';
import { Capivv, Product, Offering, PurchaseResult, ProductType } from '../../index';
import type { PluginListenerHandle } from '@capacitor/core';

export interface CapivvPaywallProps {
  /** The offering ID to display products from */
  offeringId?: string;
  /** Title displayed at the top of the paywall */
  title?: string;
  /** Subtitle displayed below the title */
  subtitle?: string;
  /** Whether to show the close button */
  showCloseButton?: boolean;
  /** Whether to show the restore purchases button */
  showRestoreButton?: boolean;
  /** List of features to display */
  features?: string[];
  /** Custom text for the purchase button */
  purchaseButtonText?: string;
  /** URL for terms of service */
  termsUrl?: string;
  /** URL for privacy policy */
  privacyUrl?: string;
  /** Enable dark mode styling */
  darkMode?: boolean;
  /** Called when a purchase completes successfully */
  onPurchaseComplete?: (result: PurchaseResult) => void;
  /** Called when a purchase fails */
  onPurchaseFailed?: (error: string) => void;
  /** Called when purchases are restored */
  onRestoreComplete?: () => void;
  /** Called when the paywall is dismissed */
  onDismiss?: () => void;
}

/**
 * Capivv Paywall Component for Ionic React
 *
 * A ready-to-use paywall component that displays available products
 * and handles the purchase flow.
 *
 * @example
 * ```tsx
 * <CapivvPaywall
 *   offeringId="default"
 *   showRestoreButton={true}
 *   onPurchaseComplete={(result) => console.log('Purchased!', result)}
 *   onDismiss={() => setShowPaywall(false)}
 * />
 * ```
 */
export const CapivvPaywall: React.FC<CapivvPaywallProps> = ({
  offeringId = 'default',
  title = 'Unlock Premium',
  subtitle,
  showCloseButton = true,
  showRestoreButton = true,
  features = [],
  purchaseButtonText = 'Subscribe Now',
  termsUrl,
  privacyUrl,
  darkMode = false,
  onPurchaseComplete,
  onPurchaseFailed,
  onRestoreComplete,
  onDismiss,
}) => {
  const [products, setProducts] = useState<Product[]>([]);
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [purchasing, setPurchasing] = useState(false);
  const [restoring, setRestoring] = useState(false);

  const loadProducts = useCallback(async () => {
    setLoading(true);
    setError(null);

    try {
      const { offerings } = await Capivv.getOfferings();
      const offering = offerings.find((o: Offering) => o.identifier === offeringId) || offerings[0];

      if (offering) {
        setProducts(offering.products);
        if (offering.products.length > 0) {
          setSelectedProduct(offering.products[0]);
        }
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to load products');
    } finally {
      setLoading(false);
    }
  }, [offeringId]);

  useEffect(() => {
    loadProducts();
  }, [loadProducts]);

  useEffect(() => {
    const listeners: PluginListenerHandle[] = [];

    const setupListeners = async () => {
      const purchaseListener = await Capivv.addListener('purchaseCompleted', (event) => {
        setPurchasing(false);
        onPurchaseComplete?.({ success: true, transaction: event.transaction });
      });
      listeners.push(purchaseListener);

      const failedListener = await Capivv.addListener('purchaseFailed', (event) => {
        setPurchasing(false);
        onPurchaseFailed?.(event.error);
      });
      listeners.push(failedListener);
    };

    setupListeners();

    return () => {
      listeners.forEach((listener) => listener.remove());
    };
  }, [onPurchaseComplete, onPurchaseFailed]);

  const handlePurchase = async () => {
    if (!selectedProduct) return;

    setPurchasing(true);

    try {
      const result = await Capivv.purchase({
        productIdentifier: selectedProduct.identifier,
        productType: selectedProduct.productType as ProductType,
      });

      if (result.success) {
        onPurchaseComplete?.(result);
      } else {
        onPurchaseFailed?.(result.error || 'Purchase failed');
      }
    } catch (e) {
      onPurchaseFailed?.(e instanceof Error ? e.message : 'Purchase failed');
    } finally {
      setPurchasing(false);
    }
  };

  const handleRestore = async () => {
    setRestoring(true);

    try {
      await Capivv.restorePurchases();
      onRestoreComplete?.();
    } catch (e) {
      onPurchaseFailed?.(e instanceof Error ? e.message : 'Restore failed');
    } finally {
      setRestoring(false);
    }
  };

  const styles = {
    paywall: {
      '--background': darkMode ? '#1a1a1a' : '#ffffff',
    } as React.CSSProperties,
    container: {
      padding: '16px',
      maxWidth: '500px',
      margin: '0 auto',
    },
    header: {
      textAlign: 'center' as const,
      marginBottom: '24px',
    },
    title: {
      fontSize: '24px',
      fontWeight: 700,
      margin: '16px 0 8px',
    },
    subtitle: {
      fontSize: '16px',
      color: 'var(--ion-color-medium)',
      margin: 0,
    },
    loading: {
      textAlign: 'center' as const,
      padding: '48px 16px',
    },
    card: {
      margin: '12px 0',
      position: 'relative' as const,
      border: '2px solid transparent',
      transition: 'border-color 0.2s ease',
    },
    selectedCard: {
      borderColor: 'var(--ion-color-primary)',
    },
    selectedIcon: {
      position: 'absolute' as const,
      top: '12px',
      right: '12px',
      fontSize: '24px',
    },
    productDescription: {
      color: 'var(--ion-color-medium)',
      marginBottom: '12px',
    },
    priceContainer: {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
    },
    price: {
      fontSize: '20px',
      fontWeight: 700,
      color: 'var(--ion-color-primary)',
    },
    trialBadge: {
      background: 'var(--ion-color-success)',
      color: 'white',
      padding: '4px 8px',
      borderRadius: '4px',
      fontSize: '12px',
      fontWeight: 600,
    },
    features: {
      marginBottom: '24px',
    },
    actions: {
      marginBottom: '24px',
    },
    footer: {
      textAlign: 'center' as const,
    },
    terms: {
      fontSize: '14px',
      color: 'var(--ion-color-medium)',
    },
    link: {
      color: 'var(--ion-color-primary)',
      cursor: 'pointer',
    },
    subscriptionTerms: {
      fontSize: '12px',
      color: 'var(--ion-color-medium)',
      marginTop: '8px',
    },
  };

  return (
    <IonContent style={styles.paywall} className={darkMode ? 'dark' : ''}>
      <div style={styles.container}>
        {/* Header */}
        <div style={styles.header}>
          {showCloseButton && (
            <IonButton fill="clear" onClick={onDismiss}>
              <IonIcon icon={closeOutline} />
            </IonButton>
          )}
          <h1 style={styles.title}>{title}</h1>
          {subtitle && <p style={styles.subtitle}>{subtitle}</p>}
        </div>

        {/* Loading State */}
        {loading && (
          <div style={styles.loading}>
            <IonSpinner />
            <p>Loading products...</p>
          </div>
        )}

        {/* Error State */}
        {error && (
          <div style={styles.loading}>
            <IonIcon icon={alertCircleOutline} color="danger" style={{ fontSize: '48px' }} />
            <p>{error}</p>
            <IonButton onClick={loadProducts}>Retry</IonButton>
          </div>
        )}

        {/* Products */}
        {!loading && !error && (
          <div style={{ marginBottom: '24px' }}>
            {products.map((product) => (
              <IonCard
                key={product.identifier}
                style={{
                  ...styles.card,
                  ...(selectedProduct?.identifier === product.identifier ? styles.selectedCard : {}),
                }}
                onClick={() => setSelectedProduct(product)}
                button
              >
                <IonCardHeader>
                  <IonCardTitle>{product.title}</IonCardTitle>
                  {product.subscriptionPeriod && (
                    <IonCardSubtitle>{product.subscriptionPeriod}</IonCardSubtitle>
                  )}
                </IonCardHeader>
                <IonCardContent>
                  <p style={styles.productDescription}>{product.description}</p>
                  <div style={styles.priceContainer}>
                    <span style={styles.price}>{product.priceString}</span>
                    {product.trialPeriod && (
                      <span style={styles.trialBadge}>{product.trialPeriod} free trial</span>
                    )}
                  </div>
                </IonCardContent>
                {selectedProduct?.identifier === product.identifier && (
                  <IonIcon
                    icon={checkmarkCircle}
                    color="primary"
                    style={styles.selectedIcon}
                  />
                )}
              </IonCard>
            ))}
          </div>
        )}

        {/* Features List */}
        {features.length > 0 && (
          <div style={styles.features}>
            <h3>What you'll get:</h3>
            <IonList lines="none">
              {features.map((feature, index) => (
                <IonItem key={index}>
                  <IonIcon icon={checkmarkCircle} color="success" slot="start" />
                  <IonLabel>{feature}</IonLabel>
                </IonItem>
              ))}
            </IonList>
          </div>
        )}

        {/* Purchase Button */}
        <div style={styles.actions}>
          <IonButton
            expand="block"
            size="large"
            disabled={!selectedProduct || purchasing}
            onClick={handlePurchase}
          >
            {purchasing ? <IonSpinner /> : purchaseButtonText}
          </IonButton>

          {showRestoreButton && (
            <IonButton
              expand="block"
              fill="clear"
              onClick={handleRestore}
              disabled={restoring}
              style={{ marginTop: '8px' }}
            >
              {restoring ? <IonSpinner name="dots" /> : 'Restore Purchases'}
            </IonButton>
          )}
        </div>

        {/* Footer */}
        <div style={styles.footer}>
          <p style={styles.terms}>
            {termsUrl && (
              <span style={styles.link} onClick={() => window.open(termsUrl, '_blank')}>
                Terms of Service
              </span>
            )}
            {termsUrl && privacyUrl && ' • '}
            {privacyUrl && (
              <span style={styles.link} onClick={() => window.open(privacyUrl, '_blank')}>
                Privacy Policy
              </span>
            )}
          </p>
          {selectedProduct?.productType === 'SUBSCRIPTION' && (
            <p style={styles.subscriptionTerms}>
              Subscription automatically renews unless cancelled at least 24 hours before the end of
              the current period.
            </p>
          )}
        </div>
      </div>
    </IonContent>
  );
};

export default CapivvPaywall;
